---


- name: Create vSphere VM
  become: false
  gather_facts: false
  hosts: ubuntu-server-2410-template.wcooke.me
  roles:
    # TODO
    # Need to make this role only run if the vm is currently running
    # - delete_vsphere_vm
    - create_vsphere_folder
    - create_vsphere_vm
    - wait_for_vsphere_vm_poweroff
    - convert_vsphere_vm_to_template
  vars_files:
    - config.yml
    - private_config.yml
